### PR TITLE
Add persistent toggle for EIS

### PR DESCRIPTION
**Pull request by ASerbinski**
When in Video mode, settings includes persistent toggle for EIS.
EIS, when enabled, will reduce the field of view.

### CODE REVIEW

**Comment by ASerbinski** [comment]
Note that this does NOT implement any form of querying for the default state for the device, not does it query if the device even supports EIS to begin with, so I think it probably needs a little extra work before merge.

**Comment by thestinger** [comment]
Yeah, we'll need that in order to merge it. I think it should be possible to do that with CameraX's Camera2Interop API using their camera info API. You can query whether it's supported and the default value if it's supported once the video mode is already started.

It's possible that it does make sense to expose this in image capture mode but it's a super niche feature and Google Camera doesn't expose super niche features since it's meant to be a point and shoot camera app rather than resembling a DSLR with a ton of configuration options. We eventually want to add DSLR-style configuration for exposure, focus, white balance, etc. but while preserving the simplicity of the interface for most users who wouldn't use those features.

**Comment by ASerbinski** [comment]
Does the device default value actually matter? I doubt very much that GCam bothers with checking the default, rather just turns on video stabilization when in video mode unless the user has manually turned it off. That would create an application level default and improve consistency between devices running this software.

I think from my point of view, we just want to query whether video stabilization is supported at all, and use that to decide if the UI element will be visible.

**Comment by ASerbinski** [comment]
Added a commit that checks if EIS is supported by the device to determine if the setting should be shown.

Tested on Pixel 6 Pro (EIS supported) and on Nexus 6 AOSP 11 (EIS not supported).

**Comment by thestinger** [comment]
@ASerbinski The reason the default might matter is because some devices may implement EIS but with a very poor quality implementation. We could just enable it by default regardless.

**Comment by thestinger** [comment]
@ASerbinski Can you rename the setting from "Include EIS" to "Enable EIS"? Include made sense for audio since it's about whether it's included in the capture or not.

**Comment by thestinger** [comment]
Some devices may also have a broken implementation.

**Comment by ASerbinski** [comment]
I'd say that if its a poor or broken implementation, it shouldn't be advertised as a feature to begin with.
I can implement that if you insist on it, but its probably overkill, and increases complexity with likely no substantial benefit.

I've made the change from include to enable, and did so throughout the code to keep it easy to follow.

**Comment by thestinger** [comment]
I squashed it into 1 commit since the other history based on the review isn't going to be helpful to others.

**Pull request merged**
